# fly.toml app configuration file generated for danielkochfi on 2023-10-04T16:43:14+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "danielkochfi"
primary_region = "arn"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
